# Generated by Django 3.2.12 on 2024-08-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField()),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
