# Generated by Django 3.2.12 on 2024-08-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('ref', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
